// import { Resend } from 'resend';
// import { NextResponse } from 'next/server';

// const resend = new Resend(process.env.RESEND_API_KEY);

// export async function POST() {
//   try {
//     const { data, error } = await resend.emails.send({
//       from: 'OmniGuard <onboarding@resend.dev>',
//       to: ['timothy12105@gmail.com'],
//       subject: '[IMPORTANT] SECURITY ALERT',
//       html: '<p>Congrats on sending your <strong>first email</strong>!</p>',
//     });

//     if (error) {
//       return NextResponse.json({ error });
//     }

//     return NextResponse.json({ data });
//   } catch (error) {
//     return NextResponse.json({ error });
//   }
// }

import { Resend } from 'resend';
import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  console.log('API route hit!');
  try {
    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not set in environment variables');
      return NextResponse.json({ error: 'Email service not configured' }, { status: 500 });
    }

    // get authenticated user from Supabase
    console.log('Getting Supabase client...');
    const supabase = await createClient();
    console.log('Getting user...');
    const {
      data: { user },
    } = await supabase.auth.getUser();
    console.log('User:', user?.email ? 'Found user with email' : 'No user or email');

    if (!user?.email) {
      return NextResponse.json({ error: 'User not authenticated or no email found' }, { status: 401 });
    }

    const body = await request.json();
    const { title, description, alertId, alertType } = body;

    const recipientEmail = user.email;
    console.log('Using authenticated user email:', recipientEmail);

    const verificationToken = `${alertId || 'alert'}-${Date.now()}`;

    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://yourapp.com';
    const verifyPath = '/security/verify';
    const dynamicLink = `${baseUrl}${verifyPath}?token=${verificationToken}&type=${alertType || 'general'}`;

    console.log('Sending email to:', recipientEmail);

    const { data, error } = await resend.emails.send({
      from: 'OmniGuard <onboarding@resend.dev>',
      to: [recipientEmail],
      subject: `[ALERT] ${title}`,
      html: `
        <h2>${title}</h2>
        <p>${description}</p>
        <p><a href="${dynamicLink}">Click here to verify this alert</a></p>
        <p><em>This alert was generated by OmniGuard's real-time monitoring system.</em></p>
      `,
    });

    if (error) {
      console.error('Error sending email:', error);
      return NextResponse.json({ error }, { status: 500 });
    }

    console.log('Email sent successfully');
    return NextResponse.json({
      success: true,
      data,
      message: 'Email sent successfully',
      link: dynamicLink,
    });
  } catch (error) {
    console.error('Exception in email API route:', error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
